// frontend/src/App.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import AnalysisPage from "./pages/AnalysisPage";
import MenuPage from "./pages/MenuPage";
import OverviewPage from "./pages/OverviewPage";
import RulesPage from "./pages/RulesPage";
import UploadPage from "./pages/UploadPage";
import { fetchDashboardData, fetchDatasets, runDataset } from "./services/api";

function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const [datasets, setDatasets] = useState([]);
  const [dataset, setDataset] = useState("A");
  const [iteration, setIteration] = useState(3);

  const [recommendations, setRecommendations] = useState({});
  const [rules, setRules] = useState([]);
  const [menuRank, setMenuRank] = useState([]);
  const [segments, setSegments] = useState({});
  const [topMeals, setTopMeals] = useState([]);

  const [loading, setLoading] = useState(false);
  const [training, setTraining] = useState(false);
  const [error, setError] = useState("");
  const [warning, setWarning] = useState("");

  const latestRequest = useRef(0);

  const activeDatasetLabel = useMemo(() => {
    const found = datasets.find((entry) => entry.id === dataset);
    return found?.label || dataset;
  }, [dataset, datasets]);

  const pageTitle = useMemo(() => {
    if (location.pathname === "/menu") return "Menu Experience";
    if (location.pathname === "/analysis") return "Visual Analytics";
    if (location.pathname === "/rules") return "Rule Intelligence";
    if (location.pathname === "/upload") return "Dataset Upload";
    return "ComboBravo Dashboard";
  }, [location.pathname]);

  const refreshDatasetsOnly = useCallback(async () => {
    try {
      const list = await fetchDatasets();
      const normalized = Array.isArray(list) ? list : [];
      setDatasets(normalized);
      if (!normalized.length) {
        setWarning(
          "No datasets found in Supabase yet. Run SQL schema, then run: npm run supabase:bootstrap."
        );
      }
      setDataset((previous) => {
        if (!normalized.length) {
          return previous;
        }
        return normalized.some((entry) => entry.id === previous)
          ? previous
          : normalized[0].id;
      });
    } catch (datasetError) {
      setError(`Failed to load dataset list: ${datasetError.message}`);
    }
  }, []);

  const loadDashboard = useCallback(async () => {
    if (!dataset || !datasets.length) {
      return;
    }

    const requestId = ++latestRequest.current;
    setLoading(true);
    setError("");
    setWarning("");

    try {
      const result = await fetchDashboardData(dataset, iteration);
      if (requestId !== latestRequest.current) {
        return;
      }

      setRecommendations(result.data.recommendations || {});
      setRules(result.data.rules || []);
      setMenuRank(result.data.menuRank || []);
      setSegments(result.data.segments || {});
      setTopMeals(result.data.topMeals || []);

      const requiredErrors = result.errors.filter((entry) => entry.required);
      const optionalErrors = result.errors.filter((entry) => !entry.required);
      if (requiredErrors.length) {
        setError(requiredErrors.map((entry) => entry.message).join(" | "));
      }
      if (optionalErrors.length) {
        setWarning(`Some sections failed: ${optionalErrors.map((entry) => entry.key).join(", ")}`);
      }
    } catch (loadError) {
      if (requestId === latestRequest.current) {
        setError(loadError.message);
      }
    } finally {
      if (requestId === latestRequest.current) {
        setLoading(false);
      }
    }
  }, [dataset, iteration, datasets.length]);

  const retrainDataset = useCallback(async () => {
    if (!dataset) {
      return;
    }
    setTraining(true);
    setError("");

    try {
      await runDataset(dataset, 3);
      await loadDashboard();
    } catch (trainError) {
      setError(trainError.message);
    } finally {
      setTraining(false);
    }
  }, [dataset, loadDashboard]);

  const handleUploaded = useCallback(
    async (datasetId) => {
      await refreshDatasetsOnly();
      if (datasetId) {
        setDataset(datasetId);
      }
      setIteration(3);
      navigate("/");
    },
    [navigate, refreshDatasetsOnly]
  );

  useEffect(() => {
    refreshDatasetsOnly();
  }, [refreshDatasetsOnly]);

  useEffect(() => {
    loadDashboard();
  }, [loadDashboard]);

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="side-brand">
          <div className="logo-placeholder" title="ComboBravo">
            <span>CB</span>
          </div>
          <div className="brand-text">
            <p className="eyebrow">Market Basket AI</p>
            <h1>ComboBravo</h1>
          </div>
        </div>

        <nav className="side-nav">
          <NavLink to="/">Dashboard</NavLink>
          <NavLink to="/menu">Menu</NavLink>
          <NavLink to="/analysis">Visuals</NavLink>
          <NavLink to="/rules">Rules</NavLink>
          <NavLink to="/upload">Upload</NavLink>
        </nav>

        <div className="side-status">
          <p>Active Dataset</p>
          <strong>{activeDatasetLabel}</strong>
          <small>Iteration {iteration}</small>
        </div>
      </aside>

      <section className="workspace">
        <header className="topbar">
          <div>
            <h2>{pageTitle}</h2>
            <p>Engine: {recommendations.engine_longterm || "-"}</p>
          </div>

          <div className="controls">
            <label>
              Dataset
              <select value={dataset} onChange={(event) => setDataset(event.target.value)}>
                {datasets.map((entry) => (
                  <option key={entry.id} value={entry.id}>
                    {entry.label}
                  </option>
                ))}
              </select>
            </label>

            <label>
              Iteration
              <div className="iteration">
                {[1, 2, 3].map((value) => (
                  <button
                    key={value}
                    className={iteration === value ? "active" : ""}
                    onClick={() => setIteration(value)}
                    type="button"
                  >
                    {value}
                  </button>
                ))}
              </div>
            </label>

            <button className="action" disabled={loading || training} onClick={retrainDataset} type="button">
              {training ? "Training..." : "Retrain"}
            </button>
          </div>
        </header>

        <main className="content">
          <section className="status-strip">
            <p>
              <span>Active:</span> {activeDatasetLabel} | Iteration {iteration}
            </p>
            <p>
              <span>Rules:</span> {recommendations.system_metrics?.n_rules_blended || 0}
            </p>
          </section>

          {error ? <section className="banner error">{error}</section> : null}
          {warning ? <section className="banner warning">{warning}</section> : null}

          <Routes>
            <Route
              path="/"
              element={
                <OverviewPage
                  loading={loading}
                  recommendations={recommendations}
                  rules={rules}
                  menuRank={menuRank}
                  topMeals={topMeals}
                />
              }
            />
            <Route
              path="/menu"
              element={<MenuPage recommendations={recommendations} topMeals={topMeals} menuRank={menuRank} />}
            />
            <Route
              path="/analysis"
              element={
                <AnalysisPage
                  topMeals={topMeals}
                  menuRank={menuRank}
                  segments={segments}
                  recommendations={recommendations}
                />
              }
            />
            <Route
              path="/rules"
              element={<RulesPage rules={rules} menuRank={menuRank} recommendations={recommendations} />}
            />
            <Route
              path="/upload"
              element={
                <UploadPage
                  datasets={datasets}
                  onUploaded={handleUploaded}
                  onRefreshRequest={refreshDatasetsOnly}
                />
              }
            />
          </Routes>
        </main>
      </section>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<template>
  <div class="app-shell">
    <header class="top-nav">
      <div class="brand">
        <p class="eyebrow">Market Basket Analysis Platform</p>
        <h1>ComboBravo</h1>
      </div>

      <nav class="nav-links">
        <RouterLink to="/">Overview</RouterLink>
        <RouterLink to="/analysis">Analysis</RouterLink>
        <RouterLink to="/rules">Rules</RouterLink>
        <RouterLink to="/upload">Upload</RouterLink>
      </nav>

      <div class="controls">
        <label>
          Dataset
          <select v-model="dataset">
            <option v-for="entry in datasets" :key="entry.id" :value="entry.id">
              {{ entry.label }}
            </option>
          </select>
        </label>

        <label>
          Iteration
          <div class="iteration">
            <button
              v-for="value in [1, 2, 3]"
              :key="value"
              :class="{ active: iteration === value }"
              @click="iteration = value"
            >
              {{ value }}
            </button>
          </div>
        </label>

        <button class="action" :disabled="loading || training" @click="retrainDataset">
          {{ training ? "Re-training..." : "Re-train" }}
        </button>
      </div>
    </header>

    <main class="content">
      <section v-if="error" class="banner error">{{ error }}</section>
      <section v-if="warning" class="banner warning">{{ warning }}</section>

      <RouterView
        :dataset="dataset"
        :datasets="datasets"
        :iteration="iteration"
        :loading="loading"
        :recommendations="recommendations"
        :rules="rules"
        :menu-rank="menuRank"
        :segments="segments"
        :top-meals="topMeals"
        @uploaded="handleUploaded"
        @refresh-request="refreshDatasetsOnly"
      />
    </main>
  </div>
</template>

<script setup>
import { ref, watch } from "vue";
import { RouterLink, RouterView, useRouter } from "vue-router";
import { fetchDashboardData, fetchDatasets, runDataset } from "./services/api";

const router = useRouter();

const datasets = ref([]);
const dataset = ref("A");
const iteration = ref(3);

const recommendations = ref({});
const rules = ref([]);
const menuRank = ref([]);
const segments = ref({});
const topMeals = ref([]);

const loading = ref(false);
const training = ref(false);
const error = ref("");
const warning = ref("");

let latestRequest = 0;

const refreshDatasetsOnly = async () => {
  try {
    const list = await fetchDatasets();
    datasets.value = list;
    if (list.length && !list.some((entry) => entry.id === dataset.value)) {
      dataset.value = list[0].id;
    }
  } catch (datasetError) {
    error.value = `Failed to load dataset list: ${datasetError.message}`;
  }
};

const loadDashboard = async () => {
  const requestId = ++latestRequest;
  loading.value = true;
  error.value = "";
  warning.value = "";

  try {
    const result = await fetchDashboardData(dataset.value, iteration.value);
    if (requestId !== latestRequest) {
      return;
    }

    recommendations.value = result.data.recommendations || {};
    rules.value = result.data.rules || [];
    menuRank.value = result.data.menuRank || [];
    segments.value = result.data.segments || {};
    topMeals.value = result.data.topMeals || [];

    const requiredErrors = result.errors.filter((entry) => entry.required);
    const optionalErrors = result.errors.filter((entry) => !entry.required);
    if (requiredErrors.length) {
      error.value = requiredErrors.map((entry) => entry.message).join(" | ");
    }
    if (optionalErrors.length) {
      warning.value = `Some sections failed: ${optionalErrors
        .map((entry) => entry.key)
        .join(", ")}`;
    }
  } catch (loadError) {
    if (requestId === latestRequest) {
      error.value = loadError.message;
    }
  } finally {
    if (requestId === latestRequest) {
      loading.value = false;
    }
  }
};

const retrainDataset = async () => {
  training.value = true;
  error.value = "";
  try {
    await runDataset(dataset.value, 3);
    await loadDashboard();
  } catch (trainError) {
    error.value = trainError.message;
  } finally {
    training.value = false;
  }
};

const handleUploaded = async (datasetId) => {
  await refreshDatasetsOnly();
  dataset.value = datasetId;
  iteration.value = 3;
  await loadDashboard();
  router.push("/");
};

watch([dataset, iteration], loadDashboard, { immediate: true });
refreshDatasetsOnly();
</script>

<style>
@import url("https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Nunito:wght@400;600;700;800&display=swap");

:root {
  --ink: #431611;
  --red: #ae2318;
  --line: #f0c8c2;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: "Nunito", sans-serif;
  background: linear-gradient(180deg, #fffdfd 0%, #fff7f6 100%);
  color: var(--ink);
}

.top-nav {
  position: sticky;
  top: 0;
  z-index: 30;
  background: #fff;
  border-bottom: 2px solid var(--line);
  display: grid;
  grid-template-columns: auto auto 1fr;
  gap: 14px;
  align-items: center;
  padding: 10px 16px;
}

.eyebrow {
  margin: 0;
  font-size: 0.7rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: #8c453d;
}

h1 {
  margin: 0;
  font-family: "Bebas Neue", sans-serif;
  color: var(--red);
  line-height: 1;
}

.nav-links {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.nav-links a {
  text-decoration: none;
  color: #7a3028;
  font-weight: 700;
  padding: 7px 10px;
  border-radius: 8px;
}

.nav-links a.router-link-active {
  background: #ffe0dc;
  color: #962016;
}

.controls {
  margin-left: auto;
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.controls label {
  display: grid;
  gap: 4px;
  font-size: 0.72rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-weight: 700;
}

.controls select {
  border: 1px solid var(--line);
  border-radius: 10px;
  background: #fff;
  color: var(--ink);
  padding: 8px 10px;
}

.iteration {
  display: flex;
  border: 1px solid var(--line);
  border-radius: 10px;
  overflow: hidden;
}

.iteration button {
  border: 0;
  padding: 8px 9px;
  background: #fff;
  color: #8d2318;
  cursor: pointer;
  font-weight: 700;
}

.iteration button.active {
  background: #ffd8d3;
}

.action {
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 8px 11px;
  color: #8f1f14;
  background: #fff4f2;
  font-weight: 700;
  cursor: pointer;
}

.action:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.content {
  width: min(1180px, 95vw);
  margin: 14px auto 28px;
  display: grid;
  gap: 10px;
}

.banner {
  border-radius: 10px;
  padding: 10px 12px;
  font-weight: 700;
}

.banner.error {
  border: 1px solid #ef9d93;
  background: #ffe5e1;
  color: #7f1c13;
}

.banner.warning {
  border: 1px solid #f0cc93;
  background: #fff5e5;
  color: #8a5a12;
}

@media (max-width: 1080px) {
  .top-nav {
    grid-template-columns: 1fr;
  }

  .controls {
    margin-left: 0;
  }
}
</style>
